### ISSUE TITLE
Review Aula 1-5

### ISSUE THREAD

**Issue by AlissonRP** [SigmaJunior/Curso_R#3]
* Aula 1: Quando sobrar tempo da uma ajeitada na formatação, tenta escrever os nomes do pacotes assim `dplyr` e não assim DPLYR 👌 
* Aula 2: Aproveitar essa aula e mostrar os shortcuts e as personalizações
* Aula 3: [Aqui](https://github.com/SigmaJunior/Curso_R#aula-03---importando-dados-definindo-caminhos-tipos-de-classes-vetor-matrizes-lista-e-dataframes-e-coerções-de-classes) fala-se sobre  "definindo caminhos", mas cadê isso na aula 3? 
  Como você vai introduzir leitura de arquivos, da pra começar com os métodos "tradicionais" (`setwd`)e dps introduzir o ambiente de Projetos do Rstudio (underrated btw), pq ai da pra conectar lá na frente com o GitHub
* Aula 4 : Talvez dividir essa aula em duas partes, deixar os loops pra parte 2, pq estruturas de controle tudo de uma vez pra quem nunca viu na vida pode ser complicado, ainda pode passar um falso entendimento.
* Aula 5: Antes de introduzir funções dentro do `R`, é interessante definir o que é função e também não entendi o que o `devtools` faz em um modelo de nivelamento??

**Comment by VitorBSP** [comment]
Certo, mas como faz pra ficar com esse sombreado no "dplyr"?

Beleza, se quiser me passar a lista de quais tu usa, pq basicamente eu só uso ctrl + 1 pra chunk.

Definindo caminhos vai ser dado no importando dados ali no ínicio com o setwd msm. 

Certo, pode ser feito sim.

Vou definir o que é funções sim, queria algum pacote para estudarmos e não achei nenhum melhor que o devtoools, porque? Pq vamos utilizar ele mais pra frente para os pacotes Mypdf1 e SigmaJr.

**Comment by AlissonRP** [comment]
Shortcurts que uso:
* mudar do console pro script e vice e versa ( `Move Focus` )
* pular pra inicio e fim de linha ( `Go to`)
* Limpar o `console` (`Clear Console`), malditos sejam os `data.frame`!
* Inserir chunk , rodar todo o chunk, rodar todos os chunks abaixo
* `help` de funções (`Show Help for Current Function`)

Falar do pacote [`styler`](https://www.tidyverse.org/blog/2017/12/styler-1.0.0/) é legal também
